Config = {}
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)

Config.SellCasinoChips = {
    coords = vector4(950.37, 34.72, 71.87, 33.82),
    radius = 1.5,
    ped = 's_m_y_casino_01'
}

Config.Products = {
    ["normal"] = {
        [1] = {
            name = "tosti",
            price = 15,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "water_bottle",
            price = 15,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "kurkakola",
            price = 15,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "twerks_candy",
            price = 15,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "snikkel_candy",
            price = 15,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "sandwich",
            price = 15,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "beer",
            price = 7,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "whiskey",
            price = 25,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "vodka",
            price = 25,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "bandage",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "lighter",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "rolling_paper",
            price = 2,
            amount = 5000,
            info = {},
            type = "item",
            slot = 12,
        },
    },
    ["liquor"] = {
        [1] = { 
            name = "vodka",     
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 1,   
        },      
        [2] = { 
            name = "curaco",       
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 2,   
        },  
        [3] = { 
            name = "schnapps",               
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 3,   
        },          
        [4] = { 
            name = "gin",      
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 4,   
        },    
        [5] = { 
            name = "scotch",     
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 5,   
        },      
        [6] = { 
            name = "rum",       
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 6,   
        },  
        [7] = { 
            name = "amaretto",               
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 7,   
        },          
        [8] = { 
            name = "bacardi",      
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 8,   
        },
        [9] = { 
            name = "jackdaniels",     
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 9,   
        },      
        [10] = { 
            name = "jager",       
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 10,   
        },  
        [11] = { 
            name = "jimbeam",               
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 11,   
        },          
        [12] = { 
            name = "smirnoff",      
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 12,   
        },
        [13] = { 
            name = "makers",     
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 13,   
        },      
        [14] = { 
            name = "champagne",       
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 14,   
        },  
        [15] = { 
            name = "patron",               
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 15,   
        },          
        [16] = { 
            name = "irishcream",      
            price = 20, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 16,   
        },
    },
    ["hardware"] = {
        [1] = {
            name = "lockpick",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_wrench",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_hammer",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "repairkit",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
            --requiredJob = { "mechanic", "police" }
        },
        [5] = {
            name = "screwdriverset",
            price = 350,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "phone",
            price = 850,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "radio",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "binoculars",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "firework1",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "firework2",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "firework3",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "firework4",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "fitbit",
            price = 400,
            amount = 150,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "cleaningkit",
            price = 150,
            amount = 150,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "advancedrepairkit",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 15,
            requiredJob = { "mechanic" }
        },
        [16] = {
            name = "drillbit",
            price = 350,
            amount = 50,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "handdrill",
            price = 1000,
            amount = 50,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "container_empty",
            price = 75,
            amount = 250,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "electricaltools",
            price = 1500,
            amount = 10,
            info = {},
            type = "item",
            slot = 19,
        },
        --[[[19] = {
            name = "lathe_tools",
            price = 1500,
            amount = 250,
            info = {},
            type = "item",
            slot = 19,
        }, 
        [20] = {
            name = "emery_cloth",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 20,
        }, 
        [21] = {
            name = "millingbits_pistol",
            price = 1000,
            amount = 250,
            info = {},
            type = "item",
            slot = 21,
        }, 
        [22] = {
            name = "millingbits_rifle",
            price = 1000,
            amount = 250,
            info = {},
            type = "item",
            slot = 22,
        }, 
        [23] = {
            name = "millingbits_shotgun",
            price = 1000,
            amount = 250,
            info = {},
            type = "item",
            slot = 23,
        }, 
        [24] = {
            name = "millingbits_machinegun",
            price = 1000,
            amount = 250,
            info = {},
            type = "item",
            slot = 24,
        }, 
        [25] = {
            name = "drillbitset",
            price = 750,
            amount = 250,
            info = {},
            type = "item",
            slot = 25,
        }, ]]
    },
    ["weedshop"] = {
        [1] = {
            name = "lighter",
            price = 5,
            amount = 1000,
            info = {},
            type = "item",
            slot = 2,
        },
        [2] = {
            name = "weed_nutrition",
            price = 2500,
            amount = 100,
            info = {},
            type = "item",
            slot = 3,
        },
        [3] = {
            name = "empty_weed_bag",
            price = 5,
            amount = 1000,
            info = {},
            type = "item",
            slot = 4,
        },
        [4] = {
            name = "rolling_paper",
            price = 2,
            amount = 1000,
            info = {},
            type = "item",
            slot = 5,
        },
    },
    ["coffeeshop"] = {
        [1] = {
            name = "frappuccino",
            price = 750,
            amount = 200,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "mocha_latte",
            price = 100,
            amount = 200,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "cappuccino",
            price = 2250,
            amount = 200,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "americano",
            price = 2,
            amount = 200,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "macciato",
            price = 2,
            amount = 200,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "irish_creme",
            price = 2,
            amount = 200,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "cold_brew",
            price = 2,
            amount = 200,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "espresso",
            price = 99,
            amount = 200,
            info = {},
            type = "item",
            slot = 8,
        },
    },
    ["gearshop"] = {
        [1] = {
            name = "diving_gear",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "jerry_can",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "fishingrod",
            price = 100,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
    },
    ["leisureshop"] = {
        [1] = {
            name = "parachute",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "binoculars",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "diving_gear",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "fishingrod",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        -- [4] = {
        --     name = "smoketrailred",
        --     price = 250,
        --     amount = 50,
        --     info = {},
        --     type = "item",
        --     slot = 4,
        -- },
    },
    ["weapons"] = {
        [1] = {
            name = "weapon_knife",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_bat",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_hatchet",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 3,
            requiredJob = { "mechanic", "police" }
        },
        [4] = {
            name = "weapon_pistol",
            price = 2500,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
            requiresLicense = true
        },
        [5] = {
            name = "weapon_snspistol",
            price = 1500,
            amount = 5,
            info = {},
            type = "item",
            slot = 5,
            requiresLicense = true
        },
        [6] = {
            name = "weapon_vintagepistol",
            price = 5400,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
            requiresLicense = true
        },
        [7] = {
            name = "pistol_ammo",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 7,
            requiresLicense = true
        },
    },
    ["coffeeplace"] = {
        [1] = {
            name = "coffee",
            price = 5,
            amount = 500,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "lighter",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
    },
    ["paint"] = {
        [1] = {
            name = "acetone",
            price = 100,
            amount = 100,
            info = {},
            type = "item",
            slot = 1,
        },
    },
    ["chemicalsupply"] = {
        [1] = {
            name = "hydrochloricacid",
            price = 100,
            amount = 100,
            info = {},
            type = "item",
            slot = 1,
        },
    },
    ["casino"] = {
        [1] = {
            name = 'casinochips',
            price = 1,
            amount = 999999,
            info = {},
            type = 'item',
            slot = 1,
        }
    },
    ["mechsupply"] = {
        [1] = {
            name = "oil",
            price = 10,
            amount = 100,
            info = {},
            type = "item",
            slot = 1,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [2] = {
            name = "tires",
            price = 50,
            amount = 100,
            info = {},
            type = "item",
            slot = 2,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },    
        [3] = {
            name = "brake_pads",
            price = 30,
            amount = 500,
            info = {},
            type = "item",
            slot = 3,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [4] = {
            name = "transmission_oil",
            price = 20,
            amount = 500,
            info = {},
            type = "item",
            slot = 4,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [5] = {
            name = "shock_absorber",
            price = 150,
            amount = 500,
            info = {},
            type = "item",
            slot = 5,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [6] = {
            name = "clutch",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 6,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [7] = {
            name = "air_filter",
            price = 40,
            amount = 500,
            info = {},
            type = "item",
            slot = 7,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [8] = {
            name = "fuel_filter",
            price = 25,
            amount = 500,
            info = {},
            type = "item",
            slot = 8,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [9] = {
            name = "spark_plugs",
            price = 16,
            amount = 500,
            info = {},
            type = "item",
            slot = 9,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [10] = {
            name = "serpentine_belt",
            price = 40,
            amount = 500,
            info = {},
            type = "item",
            slot = 10,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [11] = {
            name = "susp",
            price = 1000,
            amount = 500,
            info = {},
            type = "item",
            slot = 11,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [12] = {
            name = "susp1",
            price = 1500,
            amount = 500,
            info = {},
            type = "item",
            slot = 12,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [13] = {
            name = "susp2",
            price = 2500,
            amount = 500,
            info = {},
            type = "item",
            slot = 13,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [14] = {
            name = "susp3",
            price = 1000,
            amount = 500,
            info = {},
            type = "item",
            slot = 14,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [15] = {
            name = "susp4",
            price = 2500,
            amount = 500,
            info = {},
            type = "item",
            slot = 15,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [16] = {
            name = "garett",
            price = 6000,
            amount = 500,
            info = {},
            type = "item",
            slot = 16,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [17] = {
            name = "nitrous",
            price = 750,
            amount = 500,
            info = {},
            type = "item",
            slot = 17,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [18] = {
            name = "awd",
            price = 2000,
            amount = 500,
            info = {},
            type = "item",
            slot = 18,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [19] = {
            name = "rwd",
            price = 1500,
            amount = 500,
            info = {},
            type = "item",
            slot = 19,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [20] = {
            name = "fwd",
            price = 1000,
            amount = 500,
            info = {},
            type = "item",
            slot = 20,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [21] = {
            name = "semislick",
            price = 1000,
            amount = 500,
            info = {},
            type = "item",
            slot = 21,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [22] = {
            name = "slick",
            price = 2000,
            amount = 500,
            info = {},
            type = "item",
            slot = 22,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [23] = {
            name = "race_brakes",
            price = 2500,
            amount = 500,
            info = {},
            type = "item",
            slot = 23,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [24] = {
            name = "piston",
            price = 100,
            amount = 500,
            info = {},
            type = "item",
            slot = 24,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [25] = {
            name = "rod",
            price = 60,
            amount = 500,
            info = {},
            type = "item",
            slot = 25,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [26] = {
            name = "gear",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 26,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [27] = {
            name = "brake_discs",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 27,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [28] = {
            name = "brake_caliper",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 28,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [29] = {
            name = "springs",
            price = 75,
            amount = 500,
            info = {},
            type = "item",
            slot = 29,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [30] = {
            name = "iron",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 30,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [31] = {
            name = "aluminum",
            price = 50,
            amount = 500,
            info = {},
            type = "item",
            slot = 31,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [32] = {
            name = "scanner",
            price = 2500,
            amount = 50,
            info = {},
            type = "item",
            slot = 32,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [33] = {
            name = "engstage1",
            price = 7500,
            amount = 50,
            info = {},
            type = "item",
            slot = 33,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [34] = {
            name = "engstage2",
            price = 12500,
            amount = 50,
            info = {},
            type = "item",
            slot = 34,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [35] = {
            name = "engstage3",
            price = 17500,
            amount = 50,
            info = {},
            type = "item",
            slot = 35,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [36] = {
            name = "engstage4",
            price = 25000,
            amount = 50,
            info = {},
            type = "item",
            slot = 36,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [37] = {
            name = "transtage1",
            price = 7500,
            amount = 50,
            info = {},
            type = "item",
            slot = 37,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [38] = {
            name = "transtage2",
            price = 12500,
            amount = 50,
            info = {},
            type = "item",
            slot = 38,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [39] = {
            name = "transtage3",
            price = 17500,
            amount = 50,
            info = {},
            type = "item",
            slot = 39,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [40] = {
            name = "greddy",
            price = 2750,
            amount = 50,
            info = {},
            type = "item",
            slot = 40,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [41] = {
            name = "hks",
            price = 2750,
            amount = 50,
            info = {},
            type = "item",
            slot = 41,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [42] = {
            name = "flowmaster",
            price = 2750,
            amount = 50,
            info = {},
            type = "item",
            slot = 42,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [43] = {
            name = "skunk2",
            price = 2750,
            amount = 50,
            info = {},
            type = "item",
            slot = 43,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [44] = {
            name = "harness",
            price = 750,
            amount = 50,
            info = {},
            type = "item",
            slot = 44,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [45] = {
            name = "advancedrepairkit",
            price = 1000,
            amount = 50,
            info = {},
            type = "item",
            slot = 45,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
        [46] = {
            name = "cleaningkit",
            price = 250,
            amount = 150,
            info = {},
            type = "item",
            slot = 46,
            requiredJob = {"mechanic", "redline", "bennys", "hektic"}
        },
    },
    ["towing"] = {
        [1] = {
            name = "lockpick",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
            requiredJob = {"tow"}
        },
    },
    ["fruit"] = {              
        [1] = { 
            name = "apple",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 1,   
        },                   
        [2] = { 
            name = "pineapple",        
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 2,   
        },                   
        [3] = { 
            name = "pumpkin",   
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 3,   
        },                  
        [4] = { 
            name = "blueberry",    
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 4,   
        },      
        [5] = { 
            name = "orange",        
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 5,   
        },      
        [6] = { 
            name = "banana",     
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 6,   
        },      
        [7] = { 
            name = "cantaloupe",       
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 7,   
        },     
        [8] = { 
            name = "cherry",     
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 8,   
        },     
        [9] = { 
            name = "coconut",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 9,   
        },     
        [10] = { 
            name = "grapes",       
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 10,  
        },    
        [11] = { 
            name = "honeydew",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 11,  
        },     
        [12] = { 
            name = "kiwi",        
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 12,  
        },     
        [13] = { 
            name = "lime",   
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 13,  
        },                       
        [14] = { 
            name = "mango",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 14,  
        },        
        [15] = { 
            name = "peach",        
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 15,  
        },        
        [16] = { 
            name = "watermelon",       
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 16,  
        },    
        [17] = { 
            name = "lemon",        
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 17,  
        },               
        [18] = { 
            name = "strawberry",       
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 18,  
        },     
    },
    ["meat"] = {    
        [1] = { 
            name = "eggs",     
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 1,   
        },      
        [2] = { 
            name = "beef",       
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 2,   
        },  
        [3] = { 
            name = "groundbeef",               
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 3,   
        },          
        [4] = { 
            name = "burgerraw",      
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 4,   
        },    
        [5] = { 
            name = "ham",     
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 5,   
        },      
        [6] = { 
            name = "italiansausage",       
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 6,   
        },  
        [7] = { 
            name = "chicken",               
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 7,   
        },          
        [8] = { 
            name = "bacon",      
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 8,   
        },
        [9] = { 
            name = "squid",     
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 9,   
        },      
        [10] = { 
            name = "pork",       
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 10,   
        },  
        [11] = { 
            name = "salami",               
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 11,   
        },          
        [12] = { 
            name = "shrimp",      
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 12,   
        },
        [13] = { 
            name = "tofu",     
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 13,   
        },      
        [14] = { 
            name = "pepperoni",       
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 14,   
        },  
        [15] = { 
            name = "salmon",               
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 15,   
        },          
        [16] = { 
            name = "imitation_crab",      
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 16,   
        },
        [17] = { 
            name = "lobster",     
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 17,   
        },      
        [18] = { 
            name = "crab",       
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 18,   
        },  
        [19] = { 
            name = "clam",               
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 19,   
        },          
        [20] = { 
            name = "spam",      
            price = 10, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 20,   
        },      
    },
    ["grains"] = {    
        [1] = { 
            name = "flour",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 1,   
        },  
        [2] = { 
            name = "noodlepasta",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 2,   
        },  
        [3] = { 
            name = "rice",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 3,   
        }, 
        [4] = { 
            name = "noodleziti",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 4,   
        },  
        [5] = { 
            name = "noodlelasagna",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 5,   
        },  
        [6] = { 
            name = "noodleramen",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 6,   
        },
        [7] = { 
            name = "granola",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 7,   
        },  
        [8] = { 
            name = "bread",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 8,  
        },  
        [9] = { 
            name = "tortilla",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 9,   
        },
        [10] = { 
            name = "burgerbun",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 10,   
        },  
        [11] = { 
            name = "grain",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 11,   
        },
    },
    ["veggies"] = { 
        [1] = { 
            name = "lettuce",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 1,   
        },  
        [2] = { 
            name = "basil",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 2,   
        },  
        [3] = { 
            name = "tomato",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 3,   
        }, 
        [4] = { 
            name = "boba",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 4,   
        },  
        [5] = { 
            name = "bellpepper",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 5,   
        },  
        [6] = { 
            name = "avocado",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 6,   
        },
        [7] = { 
            name = "nori",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 7,   
        },  
        [8] = { 
            name = "redchili",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 8,  
        },  
        [9] = { 
            name = "mushroom",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 9,   
        },
        [10] = { 
            name = "onion",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 10,   
        },  
        [11] = { 
            name = "pepperoncini",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 11,   
        },  
        [12] = { 
            name = "pickle",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 12,   
        }, 
        [13] = { 
            name = "potato",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 13,   
        },
        [14] = { 
            name = "mint",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 14,   
        },  
        [15] = { 
            name = "eggplant",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 15,   
        },  
        [16] = { 
            name = "corn",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 16,   
        }, 
        [17] = { 
            name = "carrot",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 17,   
        },
    },            
    ["extras"] = { 
        [1] = { 
            name = "vanillaextract",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 1,   
        },  
        [2] = { 
            name = "sugar",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 2,   
        },  
        [3] = { 
            name = "chocolate",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 3,   
        }, 
        [4] = { 
            name = "ketchup",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 4,   
        },  
        [5] = { 
            name = "frozennugget",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 5,   
        },  
        [6] = { 
            name = "yeast",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 6,   
        },
        [7] = { 
            name = "saucebbq",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 7,   
        },  
        [8] = { 
            name = "saucetomato",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 8,  
        },  
        [9] = { 
            name = "saucealfredo",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 9,   
        },
        [10] = { 
            name = "vinegar",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 10,   
        },  
        [11] = { 
            name = "roseoil",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 11,   
        },  
        [12] = { 
            name = "cakemix",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 12,   
        }, 
        [13] = { 
            name = "chocolate_syrup",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 13,   
        },
        [14] = { 
            name = "strawberry_syrup",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 14,   
        },  
        [15] = { 
            name = "caramel_syrup",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 15,   
        },  
        [16] = { 
            name = "teabag",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 16,   
        }, 
        [17] = { 
            name = "wasabi",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 17,   
        },  
        [18] = { 
            name = "maplesyrup",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 18,   
        }, 
        [19] = { 
            name = "reddiwhip",         
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 19,   
        },
        [20] = { 
            name = "cookingoil",      
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 20,   
        },  
        [21] = { 
            name = "frosting",          
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 21,   
        },    
    },
    ["beverage"] = {
        [1] = { 
            name = "cocacola",      
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 1,   
        },  
        [2] = { 
            name = "sprite",          
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 2,   
        },  
        [3] = { 
            name = "cola",         
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 3,   
        }, 
        [4] = { 
            name = "redbull",      
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 4,   
        },  
        [5] = { 
            name = "applejuice",          
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 5,   
        },  
        [6] = { 
            name = "cranberryjuice",         
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 6,   
        },
        [7] = { 
            name = "orangejuice",      
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 7,   
        },  
        [8] = { 
            name = "pineapplejuice",          
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 8,  
        },  
        [9] = { 
            name = "tomatojuice",         
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 9,   
        },
        [10] = { 
            name = "tripplesec",      
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 10,   
        },  
        [11] = { 
            name = "simplesyrup",          
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 11,   
        },  
        [12] = { 
            name = "grenadine",         
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 12,   
        }, 
        [13] = { 
            name = "bitters",         
            price = 8, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 13,   
        },
    },

    ["dairy"] = { 
        [1] = { 
            name = "milk",     
            price = 5,  
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 1,   
        },  
        [2] = { 
            name = "cheddar", 
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 2,   
        },  
        [3] = { 
            name = "mozzshredded",     
            price = 5,  
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 3,   
        },  
        [4] = { 
            name = "parmesan", 
            price = 5, 
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 4,   
        }, 
        [5] = { 
            name = "butter",     
            price = 5,  
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 5,   
        },  
    },            
    ["pharmacy"] = { 
        [1] = { 
            name = "ephedrine",     
            price = 30,  
            amount = 50,    
            info = {},  
            type = "item",  
            slot = 1,   },  
        [2] = { 
            name = "painkillers",   
            price = 2000, 
            amount = 50,    
            info = {},  
            type = "item",  
             slot = 2,  },  
    },            
    ["event"] = {
        [1] = {
            name = "water_bottle",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 2,
        },
        [2] = {
            name = "sandwich",
            price = 2,
            amount = 100,
            info = {},
            type = "item",
            slot = 6,
        },
        [3] = {
            name = "beer",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 7,
        },
        [4] = {
            name = "whiskey",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 8,
        },
        [5] = {
            name = "vodka",
            price = 0,
            amount = 100,
            info = {},
            type = "item",
            slot = 9,
        },
    },
}

Config.Locations = {
    ["beancoffee"] = {
        ["label"] = "Bean Machine Coffee",
        ["coords"] = vector3(-633.72, 236.15, 81.88),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["coffeeplace"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },
    -- 24/7 Locations
    --[[["247supermarket"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(24.48, -1348.14, 29.5, 287.36),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["247supermarket2"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3038.34, 584.81, 7.91, 25.79),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["247supermarket3"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(-3241.7, 999.95, 12.83, 351.16),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["247supermarket4"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1727.58, 6414.67, 35.04, 246.29),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["247supermarket5"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(1960.64, 3739.33, 32.34, 325.46),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["247supermarket6"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(548.93, 2671.89, 42.16, 98.09),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["247supermarket7"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2678.57, 3279.19, 55.24, 347.68),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["247supermarket8"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(2557.81, 380.86, 108.62, 6.45),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["247supermarket9"] = {
        ["label"] = "24/7 Supermarket",
        ["coords"] = vector4(372.45, 325.78, 103.57, 268.73),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    -- LTD Gasoline Locations
    --[[["ltdgasoline"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["ltdgasoline2"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-706.06, -913.97, 19.22, 88.04),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["ltdgasoline3"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["ltdgasoline4"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1164.71, -322.94, 69.21, 101.72),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    --[[["ltdgasoline5"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },]]

    -- Rob's Liquor Locations
    ["robsliquor"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 47
    },

    ["robsliquor2"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 47
    },

    ["robsliquor3"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 47
    },

    ["robsliquor4"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 47
    },

    ["robsliquor5"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1134.2, -982.91, 46.42, 277.24),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 47
    },

    -- Hardware Store Locations
    ["hardware"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(45.68, -1749.04, 29.61, 53.13),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipcolor"] = 0
    },

    ["hardware2"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(2747.71, 3472.85, 55.67, 255.08),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipcolor"] = 0
    },

    ["hardware3"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 2.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipcolor"] = 0
    },

    -- Ammunation Locations
    ["ammunation"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-659.09, -938.68, 21.83, 91.55),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation2"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(814.86, -2155.19, 29.62, 353.86),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation3"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(1696.98, 3758.43, 34.71, 131.48),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation4"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-327.1, 6082.2, 31.45, 142.42),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation5"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(248.09, -51.8, 69.94, 339.39),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation6"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(17.07, -1107.53, 29.8, 154.85),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation7"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(2564.79, 297.43, 108.73, 273.51),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation8"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1113.41, 2698.21, 18.55, 141.6),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation9"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(841.14, -1030.04, 28.19, 265.57),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation10"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-1309.48, -394.54, 36.7, 343.63),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },
    ["ammunation11"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector4(-3168.27, 1087.43, 20.84, 153.06),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 3.0,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipcolor"] = 0
    },

    -- Casino Locations
    ["casino"] = {
        ["label"] = "Diamond Casino",
        ["coords"] = vector4(949.29, 32.13, 71.95, 79.54),
        ["ped"] = 'csb_tomcasino',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-coins",
        ["targetLabel"] = "Buy Chips",
        ["products"] = Config.Products["casino"],
        ["showblip"] = true,
        ["blipsprite"] = 617,
        ["blipcolor"] = 0
    },

    ["casinobar"] = {
        ["label"] = "Casino Bar",
        ["coords"] = vector4(937.45, 27.22, 71.83, 61.21),
        ["ped"] = 'a_m_y_smartcaspat_01',
        ["scenario"] = "WORLD_HUMAN_VALET",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    -- Weedshop Locations
    ["weedshop"] = {
        ["label"] = "Smoke On The Water",
        ["coords"] = vector4(-1171.31, -1570.89, 4.66, 130.03),
        ["ped"] = 'a_m_y_hippy_01',
        ["scenario"] = "WORLD_HUMAN_AA_SMOKE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cannabis",
        ["targetLabel"] = "Open Weed Shop",
        ["products"] = Config.Products["weedshop"],
        ["showblip"] = true,
        ["blipsprite"] = 140,
        ["blipcolor"] = 0
    },

    -- Sea Word Locations
    ["seaword"] = {
        ["label"] = "Sea Word",
        ["coords"] = vector4(-1687.03, -1072.18, 13.15, 52.93),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_IMPATIENT",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-fish",
        ["targetLabel"] = "Sea Word",
        ["products"] = Config.Products["gearshop"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    -- Leisure Shop Locations
    ["leisureshop"] = {
        ["label"] = "Leisure Shop",
        ["coords"] = vector4(-1505.91, 1511.95, 115.29, 257.13),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["leisureshop"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["mechanicshop"] = {
        ["label"] = "Mechanic Shop",
        ["coords"] = vector4(1197.15, -3253.64, 7.1, 90.74),
        ["ped"] = 's_m_y_armymech_01',
        ["scenario"] = "WORLD_HUMAN_SMOKING",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Mechanic Shop",
        ["products"] = Config.Products["mechsupply"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["towyard"] = {
        ["label"] = "Hooker Towing",
        ["coords"] = vector3(999.03, -2318.74, 30.96),
        ["ped"] = 's_m_y_armymech_01',
        ["scenario"] = "WORLD_HUMAN_SMOKING",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["towing"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["grapeseedpaint"] = {
        ["label"] = "Grapseed Paint",
        ["coords"] = vector3(1658.26, 4839.19, 42.03),
        ["ped"] = 's_m_y_armymech_01',
        ["scenario"] = "WORLD_HUMAN_SMOKING",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["paint"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["paleetopharmacy"] = {
        ["label"] = "Pharmacy",
        ["coords"] = vector3(-172.55, 6381.12, 31.47),
        ["ped"] = 's_m_y_armymech_01',
        ["scenario"] = "WORLD_HUMAN_SMOKING",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["pharmacy"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["chemicalsupply"] = {
        ["label"] = "Humane Labs",
        ["coords"] = vector3(3512.9, 3753.8, 29.97),
        ["ped"] = 's_m_y_armymech_01',
        ["scenario"] = "WORLD_HUMAN_SMOKING",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["chemicalsupply"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["walbeverage"] = {
        ["label"] = "Beverage Dept",
        ["coords"] = vector4(2732.91, 3498.86, 55.69, 164.88),
        ["ped"] = 's_f_y_sweatshop_01',
        ["scenario"] = "WORLD_HUMAN_MAID_CLEAN",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["beverage"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["walextras"] = {
        ["label"] = "Extra Dept",
        ["coords"] = vector4(2712.83, 3482.79, 55.69, 159.25),
        ["ped"] = 's_f_y_sweatshop_01',
        ["scenario"] = "WORLD_HUMAN_MAID_CLEAN",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["extras"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["walmeat"] = {
        ["label"] = "Meat Dept",
        ["coords"] = vector4(2705.01, 3492.86, 55.69, 65.59),
        ["ped"] = 's_f_y_sweatshop_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["meat"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["walfruit"] = {
        ["label"] = "Fruit Dept",
        ["coords"] = vector4(2736.6, 3469.5, 55.69, 151.63),
        ["ped"] = 's_f_y_sweatshop_01',
        ["scenario"] = "WORLD_HUMAN_STAND_IMPATIENT",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["fruit"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["waldairy"] = {
        ["label"] = "Dairy Dept",
        ["coords"] = vector4(2738.44, 3500.58, 55.69, 99.92),
        ["ped"] = 's_f_y_sweatshop_01',
        ["scenario"] = "WORLD_HUMAN_JANITOR",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["dairy"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["walveggie"] = {
        ["label"] = "Produce Dept",
        ["coords"] = vector4(2712.66, 3464.42, 55.69, 155.11),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["veggies"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["walgrains"] = {
        ["label"] = "Grains Dept",
        ["coords"] = vector4(2730.78, 3459.53, 55.69, 205.88),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["grains"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["walpharmacy"] = {
        ["label"] = "Pharmacy Dept",
        ["coords"] = vector4(2697.17, 3480.61, 55.69, 243.61),
        ["ped"] = 's_f_y_scrubs_01',
        ["scenario"] = "CODE_HUMAN_MEDIC_TIME_OF_DEATH",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["pharmacy"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },

    ["skyescoffee"] = {
        ["label"] = "Skyes Coffee Spot",
        ["coords"] = vector3(280.27, -971.76, 29.42),
        ["ped"] = 's_m_y_armymech_01',
        ["scenario"] = "WORLD_HUMAN_SMOKING",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["coffeeplace"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },
}
